name: test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: yarn cache
        uses: c-hive/gha-yarn-cache@v2

      - run: yarn install

      - name: Build
        run: yarn build

      - run: yarn test
